#PhantomMod profile: slot_1
#Sat Apr 18 13:01:00 NZST 2026
aim.aim_vertically=false
aim.click_aim=true
aim.distance=4.5
aim.fov=90.0
aim.limit_to_weapons=true
aim.require_mouse_down=true
aim.smoothing=5.0
aim.snapiness=3.0
aim.target_animals=false
aim.target_area=CENTER
aim.target_mobs=true
aim.target_mode=YAW
aim.target_players=true
aim.visibility_check=true
aimassist.enabled=false
aimassist.key=-1
alwayssprint.backwards=false
alwayssprint.enabled=true
alwayssprint.in_inventory=false
alwayssprint.key=-1
alwayssprint.sideways=false
alwayssprint.using_item=false
anti_afk.enabled=false
anti_afk.key=-1
antiafk.frequency=0.35
antiafk.keep_close=true
antiafk.max_pitch_change=6.0
antiafk.max_start_delay_seconds=45.0
antiafk.max_yaw_change=12.0
antiafk.min_start_delay_seconds=20.0
antiafk.rotation=true
antiafk.silent_aim=false
antibot.enabled=false
antibot.invisible_unlisted=true
antibot.join_grace_ticks=20
antibot.key=-1
antibot.tab_list=true
antibot.uuid_check=true
autoclicker.break_block_pause=true
autoclicker.enabled=true
autoclicker.hit_entities_only=true
autoclicker.key=-1
autoclicker.max_cps=11.0
autoclicker.min_cps=8.0
autoclicker.only_with_weapon=true
autoclicker.require_mouse_down=true
autocrystal.delay=0
autocrystal.enabled=false
autocrystal.key=-1
autocrystal.onrightclick=false
autogg.delay_ms=1000
autogg.enabled=false
autogg.key=-1
autogg.message=gg
autotools.attack_priority=SWORD_FIRST
autotools.enabled=false
autotools.key=-1
autototem.always=true
autototem.enabled=true
autototem.key=-1
autototem.threshold=10.0
autoxpthrow.enabled=false
autoxpthrow.key=46
autoxpthrow.speed=5
bedesp.color=PINK
bedesp.enabled=false
bedesp.key=-1
bedesp.range=64.0
blockhit.chance=0.65
blockhit.enabled=false
blockhit.key=-1
blockhit.mode=MANUAL
blockhit.require_mouse_down=false
blockhit.visual_animation=true
bowaim.fov=30.0
bowaim.fulldraw=true
bowaim.jitter=true
bowaim.maxdist=60.0
bowaim.mousedown=true
bowaim.players=true
bowaim.predict=true
bowaim.preset=MEDIUM
bowaim.smoothing=5.0
bowaim.team=true
bowaim.vertical=true
bowaim.visibility=true
bowaimbot.enabled=false
bowaimbot.key=-1
chestesp.chests=true
chestesp.chests.color=ORANGE
chestesp.enabled=false
chestesp.ender=true
chestesp.ender.color=PURPLE
chestesp.key=-1
chestesp.range=64.0
chestesp.trapped=true
chestesp.trapped.color=RED
criticals.chance=0.6
criticals.enabled=false
criticals.key=-1
environment.enabled=false
environment.freeze=true
environment.key=-1
environment.time=6000
environment.weather=DEFAULT
esp.animals=false
esp.enabled=true
esp.fallback_color=AQUA
esp.key=-1
esp.mobs=false
esp.players=true
esp.through_walls=true
fastplace.blocks_only=true
fastplace.delay_ticks=0
fastplace.enabled=false
fastplace.key=-1
fullbright.enabled=true
fullbright.key=-1
health.bar_scale=2.0
health.enabled=true
health.key=-1
health.max_distance=64.0
health.nametag_health=false
health.show_above_heads=false
health.show_absorption=true
health.show_bar=true
health.show_invisible=true
health.tag_scale=1.0
health.target_players=true
health.through_walls=true
hitselect.disable_during_knockback=false
hitselect.enabled=false
hitselect.in_combat_cancel_rate=100.0
hitselect.key=-1
hitselect.missed_swings_cancel_rate=0.0
hitselect.mode=BURST
hitselect.only_while_damaged=false
hitselect.pause_duration_ms=500
hitselect.wait_for_first_hit_ms=0
hud.align_left=true
hud.enabled=true
hud.key=-1
hud.show_cps=true
hud.show_fps=true
hud.show_modules=true
hud.show_ping=true
hud.stats_side=RIGHT
indicators.alert_type=THREAT
indicators.enabled=false
indicators.key=-1
indicators.only_when_approaching=false
indicators.radius_scale=1.0
indicators.render_item=true
indicators.show_arrows=true
indicators.show_distance=true
indicators.show_eggs=true
indicators.show_fireballs=true
indicators.show_pearls=true
indicators.show_potions=true
indicators.show_snowballs=true
indicators.uncommon_projectile_color=true
jumpreset.accuracy=0.8
jumpreset.chance=1.0
jumpreset.check_fov=true
jumpreset.cooldown_ticks=6
jumpreset.enabled=false
jumpreset.jump_chance_percent=100.0
jumpreset.key=-1
jumpreset.max_delay_ticks=3
jumpreset.only_when_targeting=true
jumpreset.require_mouse_down=false
jumpreset.require_moving_forward=true
jumpreset.water_check=true
latency_alerts.cooldown_seconds=10
latency_alerts.high_ping_ms=211
latency_alerts.spike_increase_ms=60
latencyalerts.enabled=false
latencyalerts.key=-1
nametags.background=true
nametags.distance_scaling=true
nametags.enabled=false
nametags.key=-1
nametags.range=96.0
nametags.scale=1.0
nametags.show_distance=false
nametags.show_health=true
nametags.show_invisible=true
nametags.show_own=true
nametags.text_shadow=true
nofall.enabled=false
nofall.key=-1
nohitdelay.chance=1.0
nohitdelay.delay=0
nohitdelay.enabled=false
nohitdelay.key=-1
nohitdelay.preset=BLATANT
nojumpdelay.enabled=false
nojumpdelay.key=-1
oreesp.coal=false
oreesp.coal.color=WHITE
oreesp.debris=true
oreesp.debris.color=ORANGE
oreesp.diamond=true
oreesp.diamond.color=CYAN
oreesp.emerald=true
oreesp.emerald.color=GREEN
oreesp.enabled=false
oreesp.gold=true
oreesp.gold.color=YELLOW
oreesp.key=-1
oreesp.lapis=true
oreesp.lapis.color=BLUE
oreesp.nether_gold=true
oreesp.nether_gold.color=YELLOW
oreesp.only_caves=false
oreesp.quartz=false
oreesp.quartz.color=WHITE
oreesp.range=32.0
oreesp.redstone=false
oreesp.redstone.color=RED
orefinder.debris_only=true
orefinder.enabled=false
orefinder.key=-1
orefinder.range=28.340401785714278
orefinder.show_directions=true
orefinder.show_list=true
orefinder.show_self=true
reach.block=5.0
reach.disable_in_water=true
reach.enabled=false
reach.entity=3.5
reach.key=-1
reach.moving_only=false
reach.only_while_sprinting=true
rightclicker.block_place_delay_ms=75
rightclicker.enabled=false
rightclicker.jitter=0.0
rightclicker.key=-1
rightclicker.max_cps=14.0
rightclicker.min_cps=10.0
rightclicker.randomization=NORMAL
rightclicker.start_delay_ms=0
rightclicker.use_item_whitelist=true
safewalk.enabled=false
safewalk.key=-1
scaffold.enabled=false
scaffold.key=-1
shulkeresp.color=PURPLE
shulkeresp.enabled=false
shulkeresp.key=-1
shulkeresp.range=64.0
silentaura.aim_vertically=false
silentaura.break_pause=true
silentaura.enabled=false
silentaura.hypixel_mode=false
silentaura.key=-1
silentaura.limit_weapons=true
silentaura.max_angle=180.0
silentaura.max_cps=12.0
silentaura.min_cps=8.0
silentaura.range=4.0
silentaura.require_mouse=false
silentaura.smoothing=5.0
silentaura.snapiness=3.0
silentaura.target_animals=false
silentaura.target_mobs=true
silentaura.target_mode=DISTANCE
silentaura.target_players=true
speedbridge.auto_off_delay=3.0
speedbridge.blocks_only=true
speedbridge.delay_ticks=3
speedbridge.sneak_on_jump=true
speedbridge_assist.enabled=false
speedbridge_assist.key=88
tnttimer.enabled=false
tnttimer.key=-1
tnttimer.scale=1.0
trajectories.color=GREEN
trajectories.enabled=true
trajectories.key=-1
trajectories.max_ticks=100.0
trajectories.only_drawing=true
trajectories.thickness=2.0
triggerbot.air_crits=true
triggerbot.early_hit_chance=0.0
triggerbot.enabled=false
triggerbot.extra_delay_ticks=0
triggerbot.key=-1
triggerbot.limit_items=true
triggerbot.require_mouse_down=true
triggerbot.shield_check=true
triggerbot.target_miss_chance=0.0
triggerbot.target_mode=BOTH
velocity.chance=1.0
velocity.disable_while_holding_s=false
velocity.enabled=false
velocity.horizontal=0.0
velocity.hypixel=false
velocity.kb=0.0
velocity.key=-1
velocity.only_while_targeting=false
velocity.vertical=0.0
waterclutch.clutch=true
waterclutch.enabled=false
waterclutch.extinguish=true
waterclutch.fire_threshold=30
waterclutch.key=-1
waterclutch.trigger_height=10
weaponcycler.combo=SWORD_AXE
weaponcycler.enabled=true
weaponcycler.key=-1
wtap.chance=1.0
wtap.cooldown_ms=250
wtap.enabled=false
wtap.key=-1
wtap.players_only=true
wtap.release_delay_ms=50
wtap.repress_delay_ms=0
wtap.select_hits=true
wtap.trigger_delay_ms=75
